apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-np-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx
      protocol: TCP
      port: 80
      nodePort: 30080
    - name: multitool
      protocol: TCP
      port: 8080
      nodePort: 30088
  type: NodePort