apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod1
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80 
        - name: multitool
          image: praqma/network-multitool
          ports: 
            - containerPort: 8080
          env: 
          - name: HTTP_PORT
            value: "8080"