apiVersion: v1
kind: PersistentVolume
metadata:
  name: echo-pv
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: "/mnt/echodata"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: echo-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1G
